track_parcel:
  fields:
    tracking_code:
      required: true
      example: "GFUS01011000000001"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "GFUS01011000000001"
      selector:
        text:
